# Base configs
baseurl: "https://jiaxiang-cheng.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Jia-Xiang Cheng"
subtitle: "See the world through my eyes!"
author: "Jia-Xiang Cheng"
header:
 title: "Photography"
 subtitle: "by Jia-Xiang Cheng"
footer:
 name: "Hey there, my name is Jia-Xiang"
 bio: "I am an engineer but deep inside I want to be an artist."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/JiaXplorer"
  instagram: "https://www.instagram.com/jiaxplore.earth"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://www.linkedin.com/in/jiaxiang-cheng/"
  github: "https://www.github.com/jiaxiang-cheng"
